### ISSUE TITLE
Sub parsers not supported

### ISSUE THREAD

**Issue by elupus** [devanshkv/argmark#3]
Subparsers don't end up documented in the output.

**Comment by elupus** [comment]
You can test with my library https://github.com/danielperna84/ha-philipsjs

```
pip install haphilipsjs
```

```bash
python -m haphilipsjs -i dummy -a 1 markdown
```

**Comment by devanshkv** [comment]
As of now, subparses aren't supported because I did not have the time to do it. However, in case you implement it, please feel free to send a PR.
