### ISSUE TITLE
question on table syntax

### ISSUE THREAD

**Issue by ynikitenko** [devanshkv/argmark#5]
Hello, thanks for your tool! In `argdown` README (I could not run or fix that program) there is a table like

    |Short|Long    |Default                |Description
    |-----|--------|-----------------------|----------------------------------------
    |`-h` |`--help`|                       |show this help message and exit
    |     |`--sum` |<built-in function max>|sum the integers (default: find the max)

In your example, it is

    |short|long|default|help|
    | :---: | :---: | :---: | :---: |
    |`-h`|`--help`||show this help message and exit|
    |`-f`|`--files`|`None`|Files to read.|

However, in Markdown specifications (like this one https://linux.die.net/man/5/pandoc_markdown) I could only find that '+' should be used on the intersection of rows and columns (however, your `|` works too). Could you please explain where you got that syntax and what it means?

**Comment by devanshkv** [comment]
I took it from https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables.

**Comment by ynikitenko** [comment]
Thank you! This really looks like "github Markdown". Anyway '+' don't work with my pandoc Markdown (I have to use your syntax).
And now I understand that `:---:` means Center-aligned (surprisingly, this also works with pandas and is displayed in `man` correctly). Many thanks.
